################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
src/webpages/diagnostic.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/diagnostic.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/diagnostic.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/diagpage.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/diagpage.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/diagpage.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/flash.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/flash.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/flash.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/flasherase.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/flasherase.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/flasherase.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/flashread.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/flashread.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/flashread.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/flashwrite.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/flashwrite.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/flashwrite.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/i2cread.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/i2cread.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/i2cread.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/i2cwrite.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/i2cwrite.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/i2cwrite.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/information.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/information.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/information.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/statistics.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/statistics.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/statistics.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/tasks.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/tasks.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/tasks.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/webpage.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/webpage.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/webpage.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

src/webpages/webserver.obj: /home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages/webserver.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: C6000 Compiler'
	"/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/bin/cl6x" -mv6600 --abi=eabi -O3 -ms2 --symdebug:none --include_path="/home/gtbldadm/ti/TI_CGT_C6000_7.4.0/include" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/pa" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/transport/ndk/nimu" --include_path="/home/gtbldadm/ti/bios_6_33_06_50/packages/ti/bios/include" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src" --include_path="/home/gtbldadm/ti/mcsdk_2_01_02_06/demos/hua/src/webpages" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/csl" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/platform" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc" --include_path="/home/gtbldadm/ti/ndk_2_21_01_38/packages/ti/ndk/inc/tools" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/qmss" --include_path="/home/gtbldadm/ti/pdk_C6678_1_1_2_6/packages/ti/drv/cppi" --define=_NDK_EXTERN_CONFIG --define=_INCLUDE_NIMU_CODE --define=C66_PLATFORMS --display_error_number --diag_warning=225 --gen_opt_info=2 --call_assumptions=3 --preproc_with_compile --preproc_dependency="src/webpages/webserver.pp" --obj_directory="src/webpages" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


